version: "3.3"
services: 
  counter:
    build: ./counter
    ports: 
      - 3001:3001
    environment: 
      - PORT=3001
      - ADDRESS=192.168.0.107
    command: npm start
    volumes: 
      - /009-docker/counter
  library:
    build: ./library
    ports: 
      - 3000:3000
    environment: 
      - PORT=3000
      - ADDRESS=192.168.0.107

    command: npm start