version: "3.3"
services: 
  counter:
    build: ./counter
    ports: 
      - 3001:3001
    env_file:
    - ./counter/.env
    command: npm start
    volumes: 
      - ./counter:/009-docker/counter
  library:
    build: ./library
    ports: 
      - 3000:3000
    env_file:
    - ./library/.env

    command: npm start